# Generated by Django 2.2.3 on 2019-08-21 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='infor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, null=True)),
                ('package', models.CharField(max_length=25)),
                ('started', models.BooleanField(default=False)),
                ('price', models.FloatField(default=0)),
                ('start', models.DateField(null=True)),
                ('end', models.DateField(null=True)),
                ('passwordkey', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
