# Generated by Django 2.2.3 on 2019-08-22 19:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infor',
            name='end',
        ),
        migrations.RemoveField(
            model_name='infor',
            name='name',
        ),
        migrations.RemoveField(
            model_name='infor',
            name='package',
        ),
        migrations.RemoveField(
            model_name='infor',
            name='price',
        ),
        migrations.RemoveField(
            model_name='infor',
            name='start',
        ),
        migrations.RemoveField(
            model_name='infor',
            name='started',
        ),
        migrations.AddField(
            model_name='infor',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
