# Generated by Django 2.2.3 on 2019-08-28 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_infor_paypal_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='infor',
            name='choice',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
