# Generated by Django 2.2.3 on 2019-09-07 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_infor_choice'),
    ]

    operations = [
        migrations.CreateModel(
            name='privacy_policy_and_terms_of_service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('privacy_policy', models.URLField(null=True)),
                ('terms_of_service', models.URLField(null=True)),
            ],
        ),
    ]
