# Generated by Django 2.2.3 on 2019-09-16 16:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('login', '0006_infor_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infor',
            name='cover',
            field=models.IntegerField(default=21),
        ),
        migrations.CreateModel(
            name='userpreferance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_mention', models.BooleanField(default=True)),
                ('activity_response', models.BooleanField(default=True)),
                ('message_recieve', models.BooleanField(default=True)),
                ('followed', models.BooleanField(default=True)),
                ('new_librick', models.BooleanField(default=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
