# Generated by Django 2.2.3 on 2019-09-16 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_auto_20190916_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infor',
            name='cover',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='infor',
            name='cover_img',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='infor',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
