# Generated by Django 2.2.3 on 2019-09-20 18:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_auto_20190916_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='infor',
            name='slug',
            field=models.SlugField(default=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
        ),
        migrations.AlterField(
            model_name='infor',
            name='cover',
            field=models.IntegerField(default=16),
        ),
    ]
