# Generated by Django 2.2.3 on 2019-09-23 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0013_auto_20190922_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='infor',
            name='profile',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='infor',
            name='cover',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='infor',
            name='profile_check',
            field=models.BooleanField(default=True),
        ),
    ]
