# Generated by Django 2.2.3 on 2019-09-23 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0014_auto_20190923_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infor',
            name='cover',
            field=models.IntegerField(default=14),
        ),
        migrations.AlterField(
            model_name='infor',
            name='profile',
            field=models.IntegerField(default='2', max_length=2),
        ),
        migrations.AlterField(
            model_name='infor',
            name='profile_check',
            field=models.BooleanField(default=False),
        ),
    ]
