# Generated by Django 2.2.3 on 2019-09-23 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0015_auto_20190923_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infor',
            name='cover',
            field=models.IntegerField(default=23),
        ),
        migrations.AlterField(
            model_name='infor',
            name='profile',
            field=models.CharField(default='1', max_length=2),
        ),
    ]
