# Generated by Django 2.2.3 on 2019-10-10 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0034_auto_20191010_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infor',
            name='cover',
            field=models.IntegerField(default=15),
        ),
    ]
