# Generated by Django 2.2.3 on 2019-10-11 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0036_auto_20191011_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infor',
            name='cover',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='infor',
            name='profile',
            field=models.IntegerField(default=2),
        ),
    ]
