# Generated by Django 2.2.3 on 2019-10-11 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0037_auto_20191011_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infor',
            name='cover',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='infor',
            name='profile',
            field=models.IntegerField(default=1),
        ),
    ]
