# Generated by Django 2.2.3 on 2019-10-16 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0039_auto_20191012_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infor',
            name='cover',
            field=models.IntegerField(default=3),
        ),
    ]
