# Generated by Django 2.2.3 on 2019-10-21 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0041_auto_20191019_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infor',
            name='cover',
            field=models.IntegerField(default=4),
        ),
    ]
