# Generated by Django 2.2.3 on 2019-10-26 18:28

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0043_auto_20191022_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='infor',
            name='amazon_code_feature',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='infor',
            name='cover',
            field=models.IntegerField(default=16),
        ),
        migrations.AlterField(
            model_name='infor',
            name='profile',
            field=models.IntegerField(default=1),
        ),
    ]
