# Generated by Django 2.2.3 on 2019-11-19 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0050_auto_20191120_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infor',
            name='cover',
            field=models.IntegerField(default=17),
        ),
    ]
