# Generated by Django 2.2.3 on 2019-12-01 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0052_auto_20191120_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infor',
            name='cover',
            field=models.IntegerField(default=7),
        ),
    ]
