# Generated by Django 2.2.3 on 2020-01-13 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0057_auto_20200105_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='infor',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='infor',
            name='cover',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='infor',
            name='profile',
            field=models.IntegerField(default=2),
        ),
    ]
