# Generated by Django 2.2.3 on 2020-01-14 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0063_auto_20200115_0221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infor',
            name='cover',
            field=models.IntegerField(default=4),
        ),
    ]
