# Generated by Django 2.2.3 on 2020-01-17 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0064_auto_20200115_0300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infor',
            name='cover',
            field=models.IntegerField(default=21),
        ),
        migrations.AlterField(
            model_name='infor',
            name='profile',
            field=models.IntegerField(default=1),
        ),
    ]
