# Generated by Django 2.2 on 2020-03-19 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0074_auto_20200316_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infor',
            name='cover',
            field=models.IntegerField(default=6),
        ),
        migrations.AlterField(
            model_name='infor',
            name='profile',
            field=models.IntegerField(default=1),
        ),
    ]
