# Generated by Django 2.2.3 on 2019-10-04 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileinfo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='posted_by',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='post',
            name='cover_photo',
        ),
        migrations.AddField(
            model_name='post',
            name='approved_by_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='facebook_link',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='image1',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='post',
            name='image2',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='post',
            name='image3',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='post',
            name='instagram_link',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='link_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='post',
            name='link_title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='linked_post',
            field=models.ManyToManyField(limit_choices_to=10, to='profileinfo.post'),
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', 'draft'), ('posted', 'posted')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='twitter_link',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='type_of_post',
            field=models.CharField(choices=[('post', 'post'), ('post part of series', 'post part of series')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='vimeo_link',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='youtube_link',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
