# Generated by Django 2.2.3 on 2019-10-06 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileinfo', '0005_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='linked_post',
            field=models.ManyToManyField(to='profileinfo.post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='type_of_post',
            field=models.CharField(choices=[('post', 'post'), ('post part of series', 'post part of series')], max_length=40, null=True),
        ),
    ]
