# Generated by Django 2.2.3 on 2019-10-06 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profileinfo', '0006_auto_20191006_1531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
