# Generated by Django 2.2.3 on 2019-10-07 19:08

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profileinfo', '0008_post_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='facebook_link',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='post',
            name='instagram_link',
        ),
        migrations.RemoveField(
            model_name='post',
            name='twitter_link',
        ),
        migrations.RemoveField(
            model_name='post',
            name='vimeo_link',
        ),
        migrations.RemoveField(
            model_name='post',
            name='youtube_link',
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor.fields.RichTextField(default='none'),
            preserve_default=False,
        ),
    ]
