# Generated by Django 2.2.3 on 2019-10-08 15:14

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profileinfo', '0009_auto_20191008_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=ckeditor.fields.RichTextField(default='title'),
            preserve_default=False,
        ),
    ]
