# Generated by Django 2.2.3 on 2019-10-08 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileinfo', '0010_auto_20191008_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', 'draft'), ('processing', 'processing')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='type_of_post',
            field=models.CharField(choices=[('single post', 'single post'), ('post part of series', 'post part of series')], max_length=40, null=True),
        ),
    ]
