# Generated by Django 2.2.3 on 2019-10-08 20:18

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profileinfo', '0011_auto_20191009_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=ckeditor.fields.RichTextField(default=''),
            preserve_default=False,
        ),
    ]
