# Generated by Django 2.2.3 on 2019-10-09 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileinfo', '0012_auto_20191009_0118'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='contentdisplay',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='titledisplay',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
