# Generated by Django 2.2.3 on 2019-10-09 17:46

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profileinfo', '0013_auto_20191009_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='commentbody',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='comment_child',
            name='commentbody',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
