# Generated by Django 2.2.3 on 2019-10-11 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileinfo', '0016_auto_20191011_0042'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='commentbodydisplay',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='comment_child',
            name='commentbodydisplay',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
