# Generated by Django 2.2.3 on 2019-10-18 19:16

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profileinfo', '0021_auto_20191016_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='amazon_code_feature',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
