# Generated by Django 2.2.3 on 2019-10-26 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profileinfo', '0024_auto_20191022_0044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='amazon_code_feature',
        ),
    ]
