# Generated by Django 2.2.3 on 2019-10-26 20:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileinfo', '0026_auto_20191026_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='contentdisplay',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='linked_post',
            field=models.ManyToManyField(blank=True, to='profileinfo.post'),
        ),
    ]
