# Generated by Django 2.2.3 on 2019-11-11 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileinfo', '0027_auto_20191027_0159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='titledisplay',
            new_name='permalink',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='commentbodydisplay',
        ),
        migrations.RemoveField(
            model_name='comment_child',
            name='commentbodydisplay',
        ),
        migrations.RemoveField(
            model_name='post',
            name='contentdisplay',
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
