# Generated by Django 2.2.3 on 2019-11-19 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileinfo', '0030_auto_20191120_0038'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='sel',
            field=models.CharField(blank=True, choices=[('post', 'post'), ('comment', 'comment'), ('child', 'child')], max_length=20),
        ),
    ]
