# Generated by Django 2.2.3 on 2019-11-19 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileinfo', '0031_notifications_sel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='relcomchild',
        ),
        migrations.AlterField(
            model_name='notifications',
            name='sel',
            field=models.CharField(blank=True, choices=[('post', 'post'), ('comment', 'comment')], max_length=20),
        ),
    ]
