# Generated by Django 2.2.3 on 2020-01-05 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profileinfo', '0034_auto_20191201_2337'),
    ]

    operations = [
        migrations.DeleteModel(
            name='message',
        ),
    ]
