# Generated by Django 2.2.3 on 2020-01-13 19:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profileinfo', '0035_delete_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='pointhistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, max_length=200)),
                ('relcom', models.ManyToManyField(to='profileinfo.comment')),
                ('relcomchild', models.ManyToManyField(to='profileinfo.comment_child')),
                ('relpost', models.ManyToManyField(to='profileinfo.post')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
