# Generated by Django 2.2.3 on 2020-01-13 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profileinfo', '0036_pointhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pointhistory',
            name='relcom',
        ),
        migrations.RemoveField(
            model_name='pointhistory',
            name='relcomchild',
        ),
    ]
