# Generated by Django 2.2.3 on 2020-01-13 19:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profileinfo', '0037_auto_20200114_0040'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointhistory',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
