# Generated by Django 2.2.3 on 2020-01-14 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileinfo', '0038_pointhistory_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='approved_by_admin_check',
            field=models.BooleanField(default=False),
        ),
    ]
