# Generated by Django 2.2.3 on 2020-01-14 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profileinfo', '0039_post_approved_by_admin_check'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='approved_by_admin_check',
            new_name='approved_by_admin_check_dont_change',
        ),
    ]
