# Generated by Django 2.2 on 2020-03-14 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileinfo', '0041_auto_20200115_0300'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Narrativa', 'Narrativa'), ('Erotico', 'Erotico'), ('Fiabe e Favole', 'Fiabe e Favole'), ('Horror', 'Horror'), ('Fantasy', 'Fantasy'), ('Sci-Fi', 'Sci-Fi'), ('Sentimenti', 'Sentimenti'), ('Umoristico', 'Umoristico'), ('Young Adult', 'Young Adult'), ('Blog', 'Blog'), ('Laboratorio di scrittura creativa', 'Laboratorio di scrittura creativa'), ('LibriCK scelti per Voi', 'LibriCK scelti per Voi'), ('Serie Top', 'Serie Top')], default='Narrativa', max_length=100),
        ),
    ]
