# Generated by Django 2.2 on 2020-03-14 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileinfo', '0042_post_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='postgallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idtag', models.CharField(default='(([[(( idtag=<built-in function id> ))]]))', max_length=30)),
                ('single_row', models.BooleanField(default=False)),
                ('infinite_scroll', models.BooleanField(default=False)),
                ('by_tag', models.BooleanField(default=False)),
                ('by_category', models.BooleanField(default=False)),
                ('by_date', models.BooleanField(default=False)),
                ('tag1', models.CharField(default='', max_length=30)),
                ('tag2', models.CharField(default='', max_length=30)),
                ('tag3', models.CharField(default='', max_length=30)),
                ('tag4', models.CharField(default='', max_length=30)),
                ('tag5', models.CharField(default='', max_length=30)),
                ('category1', models.CharField(choices=[('Narrativa', 'Narrativa'), ('Erotico', 'Erotico'), ('Fiabe e Favole', 'Fiabe e Favole'), ('Horror', 'Horror'), ('Fantasy', 'Fantasy'), ('Sci-Fi', 'Sci-Fi'), ('Sentimenti', 'Sentimenti'), ('Umoristico', 'Umoristico'), ('Young Adult', 'Young Adult'), ('Blog', 'Blog'), ('Laboratorio di scrittura creativa', 'Laboratorio di scrittura creativa'), ('LibriCK scelti per Voi', 'LibriCK scelti per Voi'), ('Serie Top', 'Serie Top')], default='', max_length=100)),
                ('category2', models.CharField(choices=[('Narrativa', 'Narrativa'), ('Erotico', 'Erotico'), ('Fiabe e Favole', 'Fiabe e Favole'), ('Horror', 'Horror'), ('Fantasy', 'Fantasy'), ('Sci-Fi', 'Sci-Fi'), ('Sentimenti', 'Sentimenti'), ('Umoristico', 'Umoristico'), ('Young Adult', 'Young Adult'), ('Blog', 'Blog'), ('Laboratorio di scrittura creativa', 'Laboratorio di scrittura creativa'), ('LibriCK scelti per Voi', 'LibriCK scelti per Voi'), ('Serie Top', 'Serie Top')], default='', max_length=100)),
                ('category3', models.CharField(choices=[('Narrativa', 'Narrativa'), ('Erotico', 'Erotico'), ('Fiabe e Favole', 'Fiabe e Favole'), ('Horror', 'Horror'), ('Fantasy', 'Fantasy'), ('Sci-Fi', 'Sci-Fi'), ('Sentimenti', 'Sentimenti'), ('Umoristico', 'Umoristico'), ('Young Adult', 'Young Adult'), ('Blog', 'Blog'), ('Laboratorio di scrittura creativa', 'Laboratorio di scrittura creativa'), ('LibriCK scelti per Voi', 'LibriCK scelti per Voi'), ('Serie Top', 'Serie Top')], default='', max_length=100)),
                ('category4', models.CharField(choices=[('Narrativa', 'Narrativa'), ('Erotico', 'Erotico'), ('Fiabe e Favole', 'Fiabe e Favole'), ('Horror', 'Horror'), ('Fantasy', 'Fantasy'), ('Sci-Fi', 'Sci-Fi'), ('Sentimenti', 'Sentimenti'), ('Umoristico', 'Umoristico'), ('Young Adult', 'Young Adult'), ('Blog', 'Blog'), ('Laboratorio di scrittura creativa', 'Laboratorio di scrittura creativa'), ('LibriCK scelti per Voi', 'LibriCK scelti per Voi'), ('Serie Top', 'Serie Top')], default='', max_length=100)),
                ('category5', models.CharField(choices=[('Narrativa', 'Narrativa'), ('Erotico', 'Erotico'), ('Fiabe e Favole', 'Fiabe e Favole'), ('Horror', 'Horror'), ('Fantasy', 'Fantasy'), ('Sci-Fi', 'Sci-Fi'), ('Sentimenti', 'Sentimenti'), ('Umoristico', 'Umoristico'), ('Young Adult', 'Young Adult'), ('Blog', 'Blog'), ('Laboratorio di scrittura creativa', 'Laboratorio di scrittura creativa'), ('LibriCK scelti per Voi', 'LibriCK scelti per Voi'), ('Serie Top', 'Serie Top')], default='', max_length=100)),
                ('category6', models.CharField(choices=[('Narrativa', 'Narrativa'), ('Erotico', 'Erotico'), ('Fiabe e Favole', 'Fiabe e Favole'), ('Horror', 'Horror'), ('Fantasy', 'Fantasy'), ('Sci-Fi', 'Sci-Fi'), ('Sentimenti', 'Sentimenti'), ('Umoristico', 'Umoristico'), ('Young Adult', 'Young Adult'), ('Blog', 'Blog'), ('Laboratorio di scrittura creativa', 'Laboratorio di scrittura creativa'), ('LibriCK scelti per Voi', 'LibriCK scelti per Voi'), ('Serie Top', 'Serie Top')], default='', max_length=100)),
                ('category7', models.CharField(choices=[('Narrativa', 'Narrativa'), ('Erotico', 'Erotico'), ('Fiabe e Favole', 'Fiabe e Favole'), ('Horror', 'Horror'), ('Fantasy', 'Fantasy'), ('Sci-Fi', 'Sci-Fi'), ('Sentimenti', 'Sentimenti'), ('Umoristico', 'Umoristico'), ('Young Adult', 'Young Adult'), ('Blog', 'Blog'), ('Laboratorio di scrittura creativa', 'Laboratorio di scrittura creativa'), ('LibriCK scelti per Voi', 'LibriCK scelti per Voi'), ('Serie Top', 'Serie Top')], default='', max_length=100)),
                ('category8', models.CharField(choices=[('Narrativa', 'Narrativa'), ('Erotico', 'Erotico'), ('Fiabe e Favole', 'Fiabe e Favole'), ('Horror', 'Horror'), ('Fantasy', 'Fantasy'), ('Sci-Fi', 'Sci-Fi'), ('Sentimenti', 'Sentimenti'), ('Umoristico', 'Umoristico'), ('Young Adult', 'Young Adult'), ('Blog', 'Blog'), ('Laboratorio di scrittura creativa', 'Laboratorio di scrittura creativa'), ('LibriCK scelti per Voi', 'LibriCK scelti per Voi'), ('Serie Top', 'Serie Top')], default='', max_length=100)),
                ('category9', models.CharField(choices=[('Narrativa', 'Narrativa'), ('Erotico', 'Erotico'), ('Fiabe e Favole', 'Fiabe e Favole'), ('Horror', 'Horror'), ('Fantasy', 'Fantasy'), ('Sci-Fi', 'Sci-Fi'), ('Sentimenti', 'Sentimenti'), ('Umoristico', 'Umoristico'), ('Young Adult', 'Young Adult'), ('Blog', 'Blog'), ('Laboratorio di scrittura creativa', 'Laboratorio di scrittura creativa'), ('LibriCK scelti per Voi', 'LibriCK scelti per Voi'), ('Serie Top', 'Serie Top')], default='', max_length=100)),
                ('category10', models.CharField(choices=[('Narrativa', 'Narrativa'), ('Erotico', 'Erotico'), ('Fiabe e Favole', 'Fiabe e Favole'), ('Horror', 'Horror'), ('Fantasy', 'Fantasy'), ('Sci-Fi', 'Sci-Fi'), ('Sentimenti', 'Sentimenti'), ('Umoristico', 'Umoristico'), ('Young Adult', 'Young Adult'), ('Blog', 'Blog'), ('Laboratorio di scrittura creativa', 'Laboratorio di scrittura creativa'), ('LibriCK scelti per Voi', 'LibriCK scelti per Voi'), ('Serie Top', 'Serie Top')], default='', max_length=100)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='postgalleryhome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('by_tag', models.BooleanField(default=False)),
                ('by_category', models.BooleanField(default=False)),
                ('by_date', models.BooleanField(default=False)),
                ('tag1', models.CharField(default='', max_length=30)),
                ('tag2', models.CharField(default='', max_length=30)),
                ('tag3', models.CharField(default='', max_length=30)),
                ('tag4', models.CharField(default='', max_length=30)),
                ('tag5', models.CharField(default='', max_length=30)),
                ('category1', models.CharField(choices=[('Narrativa', 'Narrativa'), ('Erotico', 'Erotico'), ('Fiabe e Favole', 'Fiabe e Favole'), ('Horror', 'Horror'), ('Fantasy', 'Fantasy'), ('Sci-Fi', 'Sci-Fi'), ('Sentimenti', 'Sentimenti'), ('Umoristico', 'Umoristico'), ('Young Adult', 'Young Adult'), ('Blog', 'Blog'), ('Laboratorio di scrittura creativa', 'Laboratorio di scrittura creativa'), ('LibriCK scelti per Voi', 'LibriCK scelti per Voi'), ('Serie Top', 'Serie Top')], default='', max_length=100)),
                ('category2', models.CharField(choices=[('Narrativa', 'Narrativa'), ('Erotico', 'Erotico'), ('Fiabe e Favole', 'Fiabe e Favole'), ('Horror', 'Horror'), ('Fantasy', 'Fantasy'), ('Sci-Fi', 'Sci-Fi'), ('Sentimenti', 'Sentimenti'), ('Umoristico', 'Umoristico'), ('Young Adult', 'Young Adult'), ('Blog', 'Blog'), ('Laboratorio di scrittura creativa', 'Laboratorio di scrittura creativa'), ('LibriCK scelti per Voi', 'LibriCK scelti per Voi'), ('Serie Top', 'Serie Top')], default='', max_length=100)),
                ('category3', models.CharField(choices=[('Narrativa', 'Narrativa'), ('Erotico', 'Erotico'), ('Fiabe e Favole', 'Fiabe e Favole'), ('Horror', 'Horror'), ('Fantasy', 'Fantasy'), ('Sci-Fi', 'Sci-Fi'), ('Sentimenti', 'Sentimenti'), ('Umoristico', 'Umoristico'), ('Young Adult', 'Young Adult'), ('Blog', 'Blog'), ('Laboratorio di scrittura creativa', 'Laboratorio di scrittura creativa'), ('LibriCK scelti per Voi', 'LibriCK scelti per Voi'), ('Serie Top', 'Serie Top')], default='', max_length=100)),
                ('category4', models.CharField(choices=[('Narrativa', 'Narrativa'), ('Erotico', 'Erotico'), ('Fiabe e Favole', 'Fiabe e Favole'), ('Horror', 'Horror'), ('Fantasy', 'Fantasy'), ('Sci-Fi', 'Sci-Fi'), ('Sentimenti', 'Sentimenti'), ('Umoristico', 'Umoristico'), ('Young Adult', 'Young Adult'), ('Blog', 'Blog'), ('Laboratorio di scrittura creativa', 'Laboratorio di scrittura creativa'), ('LibriCK scelti per Voi', 'LibriCK scelti per Voi'), ('Serie Top', 'Serie Top')], default='', max_length=100)),
                ('category5', models.CharField(choices=[('Narrativa', 'Narrativa'), ('Erotico', 'Erotico'), ('Fiabe e Favole', 'Fiabe e Favole'), ('Horror', 'Horror'), ('Fantasy', 'Fantasy'), ('Sci-Fi', 'Sci-Fi'), ('Sentimenti', 'Sentimenti'), ('Umoristico', 'Umoristico'), ('Young Adult', 'Young Adult'), ('Blog', 'Blog'), ('Laboratorio di scrittura creativa', 'Laboratorio di scrittura creativa'), ('LibriCK scelti per Voi', 'LibriCK scelti per Voi'), ('Serie Top', 'Serie Top')], default='', max_length=100)),
                ('category6', models.CharField(choices=[('Narrativa', 'Narrativa'), ('Erotico', 'Erotico'), ('Fiabe e Favole', 'Fiabe e Favole'), ('Horror', 'Horror'), ('Fantasy', 'Fantasy'), ('Sci-Fi', 'Sci-Fi'), ('Sentimenti', 'Sentimenti'), ('Umoristico', 'Umoristico'), ('Young Adult', 'Young Adult'), ('Blog', 'Blog'), ('Laboratorio di scrittura creativa', 'Laboratorio di scrittura creativa'), ('LibriCK scelti per Voi', 'LibriCK scelti per Voi'), ('Serie Top', 'Serie Top')], default='', max_length=100)),
                ('category7', models.CharField(choices=[('Narrativa', 'Narrativa'), ('Erotico', 'Erotico'), ('Fiabe e Favole', 'Fiabe e Favole'), ('Horror', 'Horror'), ('Fantasy', 'Fantasy'), ('Sci-Fi', 'Sci-Fi'), ('Sentimenti', 'Sentimenti'), ('Umoristico', 'Umoristico'), ('Young Adult', 'Young Adult'), ('Blog', 'Blog'), ('Laboratorio di scrittura creativa', 'Laboratorio di scrittura creativa'), ('LibriCK scelti per Voi', 'LibriCK scelti per Voi'), ('Serie Top', 'Serie Top')], default='', max_length=100)),
                ('category8', models.CharField(choices=[('Narrativa', 'Narrativa'), ('Erotico', 'Erotico'), ('Fiabe e Favole', 'Fiabe e Favole'), ('Horror', 'Horror'), ('Fantasy', 'Fantasy'), ('Sci-Fi', 'Sci-Fi'), ('Sentimenti', 'Sentimenti'), ('Umoristico', 'Umoristico'), ('Young Adult', 'Young Adult'), ('Blog', 'Blog'), ('Laboratorio di scrittura creativa', 'Laboratorio di scrittura creativa'), ('LibriCK scelti per Voi', 'LibriCK scelti per Voi'), ('Serie Top', 'Serie Top')], default='', max_length=100)),
                ('category9', models.CharField(choices=[('Narrativa', 'Narrativa'), ('Erotico', 'Erotico'), ('Fiabe e Favole', 'Fiabe e Favole'), ('Horror', 'Horror'), ('Fantasy', 'Fantasy'), ('Sci-Fi', 'Sci-Fi'), ('Sentimenti', 'Sentimenti'), ('Umoristico', 'Umoristico'), ('Young Adult', 'Young Adult'), ('Blog', 'Blog'), ('Laboratorio di scrittura creativa', 'Laboratorio di scrittura creativa'), ('LibriCK scelti per Voi', 'LibriCK scelti per Voi'), ('Serie Top', 'Serie Top')], default='', max_length=100)),
                ('category10', models.CharField(choices=[('Narrativa', 'Narrativa'), ('Erotico', 'Erotico'), ('Fiabe e Favole', 'Fiabe e Favole'), ('Horror', 'Horror'), ('Fantasy', 'Fantasy'), ('Sci-Fi', 'Sci-Fi'), ('Sentimenti', 'Sentimenti'), ('Umoristico', 'Umoristico'), ('Young Adult', 'Young Adult'), ('Blog', 'Blog'), ('Laboratorio di scrittura creativa', 'Laboratorio di scrittura creativa'), ('LibriCK scelti per Voi', 'LibriCK scelti per Voi'), ('Serie Top', 'Serie Top')], default='', max_length=100)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
            ],
        ),
    ]
