# Generated by Django 2.2 on 2020-03-15 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileinfo', '0043_postgallery_postgalleryhome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('', ''), ('Narrativa', 'Narrativa'), ('Erotico', 'Erotico'), ('Fiabe e Favole', 'Fiabe e Favole'), ('Horror', 'Horror'), ('Fantasy', 'Fantasy'), ('Sci-Fi', 'Sci-Fi'), ('Sentimenti', 'Sentimenti'), ('Umoristico', 'Umoristico'), ('Young Adult', 'Young Adult'), ('Blog', 'Blog'), ('Laboratorio di scrittura creativa', 'Laboratorio di scrittura creativa'), ('LibriCK scelti per Voi', 'LibriCK scelti per Voi'), ('Serie Top', 'Serie Top')], default='Narrativa', max_length=100),
        ),
        migrations.AlterField(
            model_name='postgallery',
            name='category1',
            field=models.CharField(choices=[('', ''), ('Narrativa', 'Narrativa'), ('Erotico', 'Erotico'), ('Fiabe e Favole', 'Fiabe e Favole'), ('Horror', 'Horror'), ('Fantasy', 'Fantasy'), ('Sci-Fi', 'Sci-Fi'), ('Sentimenti', 'Sentimenti'), ('Umoristico', 'Umoristico'), ('Young Adult', 'Young Adult'), ('Blog', 'Blog'), ('Laboratorio di scrittura creativa', 'Laboratorio di scrittura creativa'), ('LibriCK scelti per Voi', 'LibriCK scelti per Voi'), ('Serie Top', 'Serie Top')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='postgallery',
            name='category10',
            field=models.CharField(choices=[('', ''), ('Narrativa', 'Narrativa'), ('Erotico', 'Erotico'), ('Fiabe e Favole', 'Fiabe e Favole'), ('Horror', 'Horror'), ('Fantasy', 'Fantasy'), ('Sci-Fi', 'Sci-Fi'), ('Sentimenti', 'Sentimenti'), ('Umoristico', 'Umoristico'), ('Young Adult', 'Young Adult'), ('Blog', 'Blog'), ('Laboratorio di scrittura creativa', 'Laboratorio di scrittura creativa'), ('LibriCK scelti per Voi', 'LibriCK scelti per Voi'), ('Serie Top', 'Serie Top')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='postgallery',
            name='category2',
            field=models.CharField(choices=[('', ''), ('Narrativa', 'Narrativa'), ('Erotico', 'Erotico'), ('Fiabe e Favole', 'Fiabe e Favole'), ('Horror', 'Horror'), ('Fantasy', 'Fantasy'), ('Sci-Fi', 'Sci-Fi'), ('Sentimenti', 'Sentimenti'), ('Umoristico', 'Umoristico'), ('Young Adult', 'Young Adult'), ('Blog', 'Blog'), ('Laboratorio di scrittura creativa', 'Laboratorio di scrittura creativa'), ('LibriCK scelti per Voi', 'LibriCK scelti per Voi'), ('Serie Top', 'Serie Top')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='postgallery',
            name='category3',
            field=models.CharField(choices=[('', ''), ('Narrativa', 'Narrativa'), ('Erotico', 'Erotico'), ('Fiabe e Favole', 'Fiabe e Favole'), ('Horror', 'Horror'), ('Fantasy', 'Fantasy'), ('Sci-Fi', 'Sci-Fi'), ('Sentimenti', 'Sentimenti'), ('Umoristico', 'Umoristico'), ('Young Adult', 'Young Adult'), ('Blog', 'Blog'), ('Laboratorio di scrittura creativa', 'Laboratorio di scrittura creativa'), ('LibriCK scelti per Voi', 'LibriCK scelti per Voi'), ('Serie Top', 'Serie Top')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='postgallery',
            name='category4',
            field=models.CharField(choices=[('', ''), ('Narrativa', 'Narrativa'), ('Erotico', 'Erotico'), ('Fiabe e Favole', 'Fiabe e Favole'), ('Horror', 'Horror'), ('Fantasy', 'Fantasy'), ('Sci-Fi', 'Sci-Fi'), ('Sentimenti', 'Sentimenti'), ('Umoristico', 'Umoristico'), ('Young Adult', 'Young Adult'), ('Blog', 'Blog'), ('Laboratorio di scrittura creativa', 'Laboratorio di scrittura creativa'), ('LibriCK scelti per Voi', 'LibriCK scelti per Voi'), ('Serie Top', 'Serie Top')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='postgallery',
            name='category5',
            field=models.CharField(choices=[('', ''), ('Narrativa', 'Narrativa'), ('Erotico', 'Erotico'), ('Fiabe e Favole', 'Fiabe e Favole'), ('Horror', 'Horror'), ('Fantasy', 'Fantasy'), ('Sci-Fi', 'Sci-Fi'), ('Sentimenti', 'Sentimenti'), ('Umoristico', 'Umoristico'), ('Young Adult', 'Young Adult'), ('Blog', 'Blog'), ('Laboratorio di scrittura creativa', 'Laboratorio di scrittura creativa'), ('LibriCK scelti per Voi', 'LibriCK scelti per Voi'), ('Serie Top', 'Serie Top')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='postgallery',
            name='category6',
            field=models.CharField(choices=[('', ''), ('Narrativa', 'Narrativa'), ('Erotico', 'Erotico'), ('Fiabe e Favole', 'Fiabe e Favole'), ('Horror', 'Horror'), ('Fantasy', 'Fantasy'), ('Sci-Fi', 'Sci-Fi'), ('Sentimenti', 'Sentimenti'), ('Umoristico', 'Umoristico'), ('Young Adult', 'Young Adult'), ('Blog', 'Blog'), ('Laboratorio di scrittura creativa', 'Laboratorio di scrittura creativa'), ('LibriCK scelti per Voi', 'LibriCK scelti per Voi'), ('Serie Top', 'Serie Top')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='postgallery',
            name='category7',
            field=models.CharField(choices=[('', ''), ('Narrativa', 'Narrativa'), ('Erotico', 'Erotico'), ('Fiabe e Favole', 'Fiabe e Favole'), ('Horror', 'Horror'), ('Fantasy', 'Fantasy'), ('Sci-Fi', 'Sci-Fi'), ('Sentimenti', 'Sentimenti'), ('Umoristico', 'Umoristico'), ('Young Adult', 'Young Adult'), ('Blog', 'Blog'), ('Laboratorio di scrittura creativa', 'Laboratorio di scrittura creativa'), ('LibriCK scelti per Voi', 'LibriCK scelti per Voi'), ('Serie Top', 'Serie Top')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='postgallery',
            name='category8',
            field=models.CharField(choices=[('', ''), ('Narrativa', 'Narrativa'), ('Erotico', 'Erotico'), ('Fiabe e Favole', 'Fiabe e Favole'), ('Horror', 'Horror'), ('Fantasy', 'Fantasy'), ('Sci-Fi', 'Sci-Fi'), ('Sentimenti', 'Sentimenti'), ('Umoristico', 'Umoristico'), ('Young Adult', 'Young Adult'), ('Blog', 'Blog'), ('Laboratorio di scrittura creativa', 'Laboratorio di scrittura creativa'), ('LibriCK scelti per Voi', 'LibriCK scelti per Voi'), ('Serie Top', 'Serie Top')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='postgallery',
            name='category9',
            field=models.CharField(choices=[('', ''), ('Narrativa', 'Narrativa'), ('Erotico', 'Erotico'), ('Fiabe e Favole', 'Fiabe e Favole'), ('Horror', 'Horror'), ('Fantasy', 'Fantasy'), ('Sci-Fi', 'Sci-Fi'), ('Sentimenti', 'Sentimenti'), ('Umoristico', 'Umoristico'), ('Young Adult', 'Young Adult'), ('Blog', 'Blog'), ('Laboratorio di scrittura creativa', 'Laboratorio di scrittura creativa'), ('LibriCK scelti per Voi', 'LibriCK scelti per Voi'), ('Serie Top', 'Serie Top')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='postgalleryhome',
            name='category1',
            field=models.CharField(blank=True, choices=[('', ''), ('Narrativa', 'Narrativa'), ('Erotico', 'Erotico'), ('Fiabe e Favole', 'Fiabe e Favole'), ('Horror', 'Horror'), ('Fantasy', 'Fantasy'), ('Sci-Fi', 'Sci-Fi'), ('Sentimenti', 'Sentimenti'), ('Umoristico', 'Umoristico'), ('Young Adult', 'Young Adult'), ('Blog', 'Blog'), ('Laboratorio di scrittura creativa', 'Laboratorio di scrittura creativa'), ('LibriCK scelti per Voi', 'LibriCK scelti per Voi'), ('Serie Top', 'Serie Top')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='postgalleryhome',
            name='category10',
            field=models.CharField(blank=True, choices=[('', ''), ('Narrativa', 'Narrativa'), ('Erotico', 'Erotico'), ('Fiabe e Favole', 'Fiabe e Favole'), ('Horror', 'Horror'), ('Fantasy', 'Fantasy'), ('Sci-Fi', 'Sci-Fi'), ('Sentimenti', 'Sentimenti'), ('Umoristico', 'Umoristico'), ('Young Adult', 'Young Adult'), ('Blog', 'Blog'), ('Laboratorio di scrittura creativa', 'Laboratorio di scrittura creativa'), ('LibriCK scelti per Voi', 'LibriCK scelti per Voi'), ('Serie Top', 'Serie Top')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='postgalleryhome',
            name='category2',
            field=models.CharField(blank=True, choices=[('', ''), ('Narrativa', 'Narrativa'), ('Erotico', 'Erotico'), ('Fiabe e Favole', 'Fiabe e Favole'), ('Horror', 'Horror'), ('Fantasy', 'Fantasy'), ('Sci-Fi', 'Sci-Fi'), ('Sentimenti', 'Sentimenti'), ('Umoristico', 'Umoristico'), ('Young Adult', 'Young Adult'), ('Blog', 'Blog'), ('Laboratorio di scrittura creativa', 'Laboratorio di scrittura creativa'), ('LibriCK scelti per Voi', 'LibriCK scelti per Voi'), ('Serie Top', 'Serie Top')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='postgalleryhome',
            name='category3',
            field=models.CharField(blank=True, choices=[('', ''), ('Narrativa', 'Narrativa'), ('Erotico', 'Erotico'), ('Fiabe e Favole', 'Fiabe e Favole'), ('Horror', 'Horror'), ('Fantasy', 'Fantasy'), ('Sci-Fi', 'Sci-Fi'), ('Sentimenti', 'Sentimenti'), ('Umoristico', 'Umoristico'), ('Young Adult', 'Young Adult'), ('Blog', 'Blog'), ('Laboratorio di scrittura creativa', 'Laboratorio di scrittura creativa'), ('LibriCK scelti per Voi', 'LibriCK scelti per Voi'), ('Serie Top', 'Serie Top')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='postgalleryhome',
            name='category4',
            field=models.CharField(blank=True, choices=[('', ''), ('Narrativa', 'Narrativa'), ('Erotico', 'Erotico'), ('Fiabe e Favole', 'Fiabe e Favole'), ('Horror', 'Horror'), ('Fantasy', 'Fantasy'), ('Sci-Fi', 'Sci-Fi'), ('Sentimenti', 'Sentimenti'), ('Umoristico', 'Umoristico'), ('Young Adult', 'Young Adult'), ('Blog', 'Blog'), ('Laboratorio di scrittura creativa', 'Laboratorio di scrittura creativa'), ('LibriCK scelti per Voi', 'LibriCK scelti per Voi'), ('Serie Top', 'Serie Top')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='postgalleryhome',
            name='category5',
            field=models.CharField(blank=True, choices=[('', ''), ('Narrativa', 'Narrativa'), ('Erotico', 'Erotico'), ('Fiabe e Favole', 'Fiabe e Favole'), ('Horror', 'Horror'), ('Fantasy', 'Fantasy'), ('Sci-Fi', 'Sci-Fi'), ('Sentimenti', 'Sentimenti'), ('Umoristico', 'Umoristico'), ('Young Adult', 'Young Adult'), ('Blog', 'Blog'), ('Laboratorio di scrittura creativa', 'Laboratorio di scrittura creativa'), ('LibriCK scelti per Voi', 'LibriCK scelti per Voi'), ('Serie Top', 'Serie Top')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='postgalleryhome',
            name='category6',
            field=models.CharField(blank=True, choices=[('', ''), ('Narrativa', 'Narrativa'), ('Erotico', 'Erotico'), ('Fiabe e Favole', 'Fiabe e Favole'), ('Horror', 'Horror'), ('Fantasy', 'Fantasy'), ('Sci-Fi', 'Sci-Fi'), ('Sentimenti', 'Sentimenti'), ('Umoristico', 'Umoristico'), ('Young Adult', 'Young Adult'), ('Blog', 'Blog'), ('Laboratorio di scrittura creativa', 'Laboratorio di scrittura creativa'), ('LibriCK scelti per Voi', 'LibriCK scelti per Voi'), ('Serie Top', 'Serie Top')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='postgalleryhome',
            name='category7',
            field=models.CharField(blank=True, choices=[('', ''), ('Narrativa', 'Narrativa'), ('Erotico', 'Erotico'), ('Fiabe e Favole', 'Fiabe e Favole'), ('Horror', 'Horror'), ('Fantasy', 'Fantasy'), ('Sci-Fi', 'Sci-Fi'), ('Sentimenti', 'Sentimenti'), ('Umoristico', 'Umoristico'), ('Young Adult', 'Young Adult'), ('Blog', 'Blog'), ('Laboratorio di scrittura creativa', 'Laboratorio di scrittura creativa'), ('LibriCK scelti per Voi', 'LibriCK scelti per Voi'), ('Serie Top', 'Serie Top')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='postgalleryhome',
            name='category8',
            field=models.CharField(blank=True, choices=[('', ''), ('Narrativa', 'Narrativa'), ('Erotico', 'Erotico'), ('Fiabe e Favole', 'Fiabe e Favole'), ('Horror', 'Horror'), ('Fantasy', 'Fantasy'), ('Sci-Fi', 'Sci-Fi'), ('Sentimenti', 'Sentimenti'), ('Umoristico', 'Umoristico'), ('Young Adult', 'Young Adult'), ('Blog', 'Blog'), ('Laboratorio di scrittura creativa', 'Laboratorio di scrittura creativa'), ('LibriCK scelti per Voi', 'LibriCK scelti per Voi'), ('Serie Top', 'Serie Top')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='postgalleryhome',
            name='category9',
            field=models.CharField(blank=True, choices=[('', ''), ('Narrativa', 'Narrativa'), ('Erotico', 'Erotico'), ('Fiabe e Favole', 'Fiabe e Favole'), ('Horror', 'Horror'), ('Fantasy', 'Fantasy'), ('Sci-Fi', 'Sci-Fi'), ('Sentimenti', 'Sentimenti'), ('Umoristico', 'Umoristico'), ('Young Adult', 'Young Adult'), ('Blog', 'Blog'), ('Laboratorio di scrittura creativa', 'Laboratorio di scrittura creativa'), ('LibriCK scelti per Voi', 'LibriCK scelti per Voi'), ('Serie Top', 'Serie Top')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='postgalleryhome',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='postgalleryhome',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='postgalleryhome',
            name='tag1',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='postgalleryhome',
            name='tag2',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='postgalleryhome',
            name='tag3',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='postgalleryhome',
            name='tag4',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='postgalleryhome',
            name='tag5',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
