# Generated by Django 2.2 on 2020-03-16 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileinfo', '0044_auto_20200315_2204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postgallery',
            name='idtag',
        ),
        migrations.AddField(
            model_name='postgallery',
            name='idtag_use_after_creation',
            field=models.CharField(default='(([[(( idtag=<built-in function id> ))]]))', editable=False, max_length=30),
        ),
    ]
