# Generated by Django 2.2 on 2020-03-16 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileinfo', '0045_auto_20200316_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postgallery',
            name='category1',
            field=models.CharField(blank=True, choices=[('', ''), ('Narrativa', 'Narrativa'), ('Erotico', 'Erotico'), ('Fiabe e Favole', 'Fiabe e Favole'), ('Horror', 'Horror'), ('Fantasy', 'Fantasy'), ('Sci-Fi', 'Sci-Fi'), ('Sentimenti', 'Sentimenti'), ('Umoristico', 'Umoristico'), ('Young Adult', 'Young Adult'), ('Blog', 'Blog'), ('Laboratorio di scrittura creativa', 'Laboratorio di scrittura creativa'), ('LibriCK scelti per Voi', 'LibriCK scelti per Voi'), ('Serie Top', 'Serie Top')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='postgallery',
            name='category10',
            field=models.CharField(blank=True, choices=[('', ''), ('Narrativa', 'Narrativa'), ('Erotico', 'Erotico'), ('Fiabe e Favole', 'Fiabe e Favole'), ('Horror', 'Horror'), ('Fantasy', 'Fantasy'), ('Sci-Fi', 'Sci-Fi'), ('Sentimenti', 'Sentimenti'), ('Umoristico', 'Umoristico'), ('Young Adult', 'Young Adult'), ('Blog', 'Blog'), ('Laboratorio di scrittura creativa', 'Laboratorio di scrittura creativa'), ('LibriCK scelti per Voi', 'LibriCK scelti per Voi'), ('Serie Top', 'Serie Top')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='postgallery',
            name='category2',
            field=models.CharField(blank=True, choices=[('', ''), ('Narrativa', 'Narrativa'), ('Erotico', 'Erotico'), ('Fiabe e Favole', 'Fiabe e Favole'), ('Horror', 'Horror'), ('Fantasy', 'Fantasy'), ('Sci-Fi', 'Sci-Fi'), ('Sentimenti', 'Sentimenti'), ('Umoristico', 'Umoristico'), ('Young Adult', 'Young Adult'), ('Blog', 'Blog'), ('Laboratorio di scrittura creativa', 'Laboratorio di scrittura creativa'), ('LibriCK scelti per Voi', 'LibriCK scelti per Voi'), ('Serie Top', 'Serie Top')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='postgallery',
            name='category3',
            field=models.CharField(blank=True, choices=[('', ''), ('Narrativa', 'Narrativa'), ('Erotico', 'Erotico'), ('Fiabe e Favole', 'Fiabe e Favole'), ('Horror', 'Horror'), ('Fantasy', 'Fantasy'), ('Sci-Fi', 'Sci-Fi'), ('Sentimenti', 'Sentimenti'), ('Umoristico', 'Umoristico'), ('Young Adult', 'Young Adult'), ('Blog', 'Blog'), ('Laboratorio di scrittura creativa', 'Laboratorio di scrittura creativa'), ('LibriCK scelti per Voi', 'LibriCK scelti per Voi'), ('Serie Top', 'Serie Top')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='postgallery',
            name='category4',
            field=models.CharField(blank=True, choices=[('', ''), ('Narrativa', 'Narrativa'), ('Erotico', 'Erotico'), ('Fiabe e Favole', 'Fiabe e Favole'), ('Horror', 'Horror'), ('Fantasy', 'Fantasy'), ('Sci-Fi', 'Sci-Fi'), ('Sentimenti', 'Sentimenti'), ('Umoristico', 'Umoristico'), ('Young Adult', 'Young Adult'), ('Blog', 'Blog'), ('Laboratorio di scrittura creativa', 'Laboratorio di scrittura creativa'), ('LibriCK scelti per Voi', 'LibriCK scelti per Voi'), ('Serie Top', 'Serie Top')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='postgallery',
            name='category5',
            field=models.CharField(blank=True, choices=[('', ''), ('Narrativa', 'Narrativa'), ('Erotico', 'Erotico'), ('Fiabe e Favole', 'Fiabe e Favole'), ('Horror', 'Horror'), ('Fantasy', 'Fantasy'), ('Sci-Fi', 'Sci-Fi'), ('Sentimenti', 'Sentimenti'), ('Umoristico', 'Umoristico'), ('Young Adult', 'Young Adult'), ('Blog', 'Blog'), ('Laboratorio di scrittura creativa', 'Laboratorio di scrittura creativa'), ('LibriCK scelti per Voi', 'LibriCK scelti per Voi'), ('Serie Top', 'Serie Top')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='postgallery',
            name='category6',
            field=models.CharField(blank=True, choices=[('', ''), ('Narrativa', 'Narrativa'), ('Erotico', 'Erotico'), ('Fiabe e Favole', 'Fiabe e Favole'), ('Horror', 'Horror'), ('Fantasy', 'Fantasy'), ('Sci-Fi', 'Sci-Fi'), ('Sentimenti', 'Sentimenti'), ('Umoristico', 'Umoristico'), ('Young Adult', 'Young Adult'), ('Blog', 'Blog'), ('Laboratorio di scrittura creativa', 'Laboratorio di scrittura creativa'), ('LibriCK scelti per Voi', 'LibriCK scelti per Voi'), ('Serie Top', 'Serie Top')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='postgallery',
            name='category7',
            field=models.CharField(blank=True, choices=[('', ''), ('Narrativa', 'Narrativa'), ('Erotico', 'Erotico'), ('Fiabe e Favole', 'Fiabe e Favole'), ('Horror', 'Horror'), ('Fantasy', 'Fantasy'), ('Sci-Fi', 'Sci-Fi'), ('Sentimenti', 'Sentimenti'), ('Umoristico', 'Umoristico'), ('Young Adult', 'Young Adult'), ('Blog', 'Blog'), ('Laboratorio di scrittura creativa', 'Laboratorio di scrittura creativa'), ('LibriCK scelti per Voi', 'LibriCK scelti per Voi'), ('Serie Top', 'Serie Top')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='postgallery',
            name='category8',
            field=models.CharField(blank=True, choices=[('', ''), ('Narrativa', 'Narrativa'), ('Erotico', 'Erotico'), ('Fiabe e Favole', 'Fiabe e Favole'), ('Horror', 'Horror'), ('Fantasy', 'Fantasy'), ('Sci-Fi', 'Sci-Fi'), ('Sentimenti', 'Sentimenti'), ('Umoristico', 'Umoristico'), ('Young Adult', 'Young Adult'), ('Blog', 'Blog'), ('Laboratorio di scrittura creativa', 'Laboratorio di scrittura creativa'), ('LibriCK scelti per Voi', 'LibriCK scelti per Voi'), ('Serie Top', 'Serie Top')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='postgallery',
            name='category9',
            field=models.CharField(blank=True, choices=[('', ''), ('Narrativa', 'Narrativa'), ('Erotico', 'Erotico'), ('Fiabe e Favole', 'Fiabe e Favole'), ('Horror', 'Horror'), ('Fantasy', 'Fantasy'), ('Sci-Fi', 'Sci-Fi'), ('Sentimenti', 'Sentimenti'), ('Umoristico', 'Umoristico'), ('Young Adult', 'Young Adult'), ('Blog', 'Blog'), ('Laboratorio di scrittura creativa', 'Laboratorio di scrittura creativa'), ('LibriCK scelti per Voi', 'LibriCK scelti per Voi'), ('Serie Top', 'Serie Top')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='postgallery',
            name='tag1',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='postgallery',
            name='tag2',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='postgallery',
            name='tag3',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='postgallery',
            name='tag4',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='postgallery',
            name='tag5',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
