# Generated by Django 2.2 on 2020-03-16 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileinfo', '0048_auto_20200316_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postgallery',
            name='idtag_use_after_creation',
            field=models.CharField(default='(([[(( idtag=<built-in function id> ))]]))', max_length=50),
        ),
    ]
