# Generated by Django 2.2 on 2020-03-19 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileinfo', '0049_auto_20200316_2218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postgallery',
            name='infinite_scroll',
        ),
        migrations.RemoveField(
            model_name='postgallery',
            name='single_row',
        ),
        migrations.AddField(
            model_name='postgallery',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='postgallery',
            name='idtag_use_after_creation',
            field=models.CharField(default='(([[((==idtag', max_length=50),
        ),
    ]
